### ISSUE TITLE
Search function on Crop Ontology Tree page

### ISSUE THREAD

**Issue by TomHazekam** [bioversity/Crop-Ontology#166] opened 2021-09-08 14:23 UTC
There is a "Google"-style search on the home-page. It would be useful to have such a search function on each of the CO "Tree" pages as well. Ideally this search should be restricted to the crop in question.

**Comment by marieALaporte** [comment] 2023-05-24 07:11
Close as it is a duplicate of #189

**Closed as completed by marieALaporte** 2023-05-24 07:11 UTC
Labels: new site
